### ISSUE TITLE
ulimit -n, collect-web.js

### ISSUE THREAD

**Issue by oeon** [tmcw/landpatch#3]
For me, in OS X..running `ulimit -n` (in Terminal) returns `256`. This was leading to the error below when executing `node collect-web.js`:

```
loading LC80470112013207LGN00
loading LC80470122013287LGN00
loading LC80470132014034LGN00

Error: spawn EMFILE
    at errnoException (child_process.js:988:11)
    at ChildProcess.spawn (child_process.js:935:11)
    at exports.spawn (child_process.js:723:9)
    at Duplex._spawn (/Users/joe/landpatch/node_modules/imagemagick-stream/index.js:229:14)
    at process._tickCallback (node.js:415:13)
```

A few webpages said the max is something around 10,000 - so I ran `ulimit -n 10000`, then `collect-web.js` worked for me as expected. Not sure if this was particular to my case or may be useful in the README

**Comment by tmcw** [comment]
Thanks Joe! Added a note in the README and referenced this issue in the commit.

**Comment by oeon** [comment]
omg

> 2 years ago

I had forgotten about this...thanks, Tom!
